# +-----------------------------------------------+ #
# <                 Configuration                 > #
# +-----------------------------------------------+ #
CheckUpdates: true
Inventories:
  MaximumPerPlayer: 3