name: ItemCondenser
version: 3.5
author: ShortCircuit908
website: http://dev.bukkit.org/bukkit-plugins/itemcondenser/
main: com.shortcircuit.itemcondenser.ItemCondenser
description: Inventory management tools
commands:
  drop:
    description: Drops the item in hand to where the player is looking
    usage: /<command>
    permission: ItemCondenser.Items.Drop
  dropall:
    description: Drops all items in the player's inventory to where the player is looking
    usage: /<command>
    permission: ItemCondenser.Items.DropAll
  store:
    description: Stores the item in hand in the chest the player is looking at
    usage: /<command>
    permission: ItemCondenser.Items.Store
  storeall:
    description: Stores all the items in the player's inventory in the chest the player is looking at
    usage: /<command>
    permission: ItemCondenser.Items.StoreAll
  condense:
    description: Condenses the player's materials into blocks
    usage: /<command> [chest]
    permission: ItemCondenser.Condense
  etable:
    description: Opens a portable enchanting table
    usage: /<command>
    permission: ItemCondenser.Utility.Enchant
  echest:
    description: Opens the player's ender chest
    usage: /<command>
    permission: ItemCondenser.Utility.EnderChest
  ctable:
    description: Opens a portable 3x3 crafting grid
    usage: /<command>
    permission: ItemCondenser.Utility.Craft
  anvil:
    description: Opens a portable anvil
    usage: /<command>
    permission: ItemCondenser.Utility.Repair
  brew:
    description: Opens a portable brewing stand
    usage: /<command>
    permission: ItemCondenser.Utility.Brew
  smelt:
    description: Opens a portable furnace
    usage: /<command>
    permission: ItemCondenser.Utility.Smelt
  trash:
    description: Opens a trash can
    usage: /<command>
    permission: ItemCondenser.Utility.Trash
  sort:
    description: Condenses all stray items into one stack.
    usage: /<command> [chest]
    permission: ItemCondenser.Sort
  clear:
    description: Clears the player's inventory
    usage: /<command> [chest]
    permission: ItemCondenser.Clear
  invcreate:
    description: Creates another player inventory
    usage: /<command> <InventoryName>
    permission: ItemCondenser.Inventories.Create
  invopen:
    description: Opens an existing additional inventory
    usage: /<command> <InventoryName>
    permission: ItemCondenser.Inventories.Open
  invremove:
    description: Deletes an existing additional inventory
    usage: /<command> <InventoryName>
    permission: ItemCondenser.Inventories.Remove
  invlist:
    description: Lists the player's additional inventories
    usage: /<command>
    permission: ItemCondenser.Inventories.List
  itemname:
    description: Rename the item in the player's hand hand
    usage: /<command> <Remove|ItemName>
    permission: ItemCondenser.Items.Name
  itemlore:
    description: Append to, or clear, the item's lore
    usage: /<command> <Remove|ItemLore>
    permission: ItemCondenser.Items.Lore
  moreitems:
    description: Give the player a full stack of the item in the player's hand
    usage: /<command>
    permission: ItemCondenser.Items.More
permissons:
  ItemCondenser.*:
    description: Gives access to all ItemCondenser commands
    children:
      ItemCondenser.Utility.Craft: true
      ItemCondenser.Utility.EnderChest: true
      ItemCondenser.Utility.Repair: true
      ItemCondenser.Utility.Brew: true
      ItemCondenser.Utility.Smelt: true
      ItemCondenser.Utility.Trash: true
      ItemCondenser.Utility.Enchant: true
      ItemCondenser.Items.Store: true
      ItemCondenser.Items.StoreAll: true
      ItemCondenser.Items.Drop: true
      ItemCondenser.Items.DropAll: true
      ItemCondenser.Items.Name: true
      ItemCondenser.Items.Lore: true
      ItemCondenser.Items.More: true
      ItemCondenser.Inventories.Create: true
      ItemCondenser.Inventories.Create.Infinite: true
      ItemCondenser.Inventories.Open: true
      ItemCondenser.Inventories.Remove: true
      ItemCondenser.Inventories.List: true
      ItemCondenser.Sort: true
      ItemCondenser.Clear: true
      ItemCondenser.Condense: true
    default: op